version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sidedominicana
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: sidedominicana:1.3
    container_name: my_app
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:sidedominicana@postgres_db:5432/postgres
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./certs:/usr/certs
    working_dir: /usr/src/app
    command: ["node", "index.js"]

volumes:
  postgres_data:
