# Use a stable Node.js version
FROM node:20

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production

# Copy the application source code
COPY . .

# Build the React client
WORKDIR /app/client-admin
RUN npm install
RUN npm run build

# Install a lightweight HTTP server
RUN npm install -g serve

# Serve the React app on port 80
CMD ["serve", "-s", "build", "-l", "80"]

# Expose port 80
EXPOSE 80
