FROM node:18

WORKDIR /usr/src/app

# Copy backend code and install
COPY package*.json ./
RUN npm install

COPY . .

# Build the React app
WORKDIR /usr/src/app/client-admin
RUN npm install
RUN npm run build

# Go back to backend root
WORKDIR /usr/src/app

# Ports
EXPOSE 80
EXPOSE 443

CMD ["node", "index.js"]
